---
title: "mysimplecompendium"
output:
    bookdown::html_document2:
      base_format: rmarkdown::html_vignette
      number_sections: false
bibliography: example.bib
vignette: >
  %\VignetteIndexEntry{mysimplecompendium}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 5,
  fig.retina = 2,
  comment = "#>",
  devtools::load_all(".")
)
```

```{r setup}
library(mysimplecompendium)
```


```{r starwars-gender-plot, fig.cap="Gender of Starwars characters"}
library(tidyverse)
library(here)
```
```{r starwarsplot, fig.cap="A ggplot of starwars stuff"}
library(tidyverse)
starwars %>%
  filter(species=="Human") %>%
  ggplot() +
  aes(x=height,y=mass)+
  geom_point()
```

We can see Figure \@ref(fig:starwarsplot)...


And R script files:

```{r}
source(here("vignettes/myscript.R"))
plus_two(c(2,3))
```

Here is an article "Terminologies for reproducible research". [@clarkson2017human].

## References cited



